package org.fluttercode.datafactory.hun_impl

import org.fluttercode.datafactory.AddressDataValues

class HungarianAddressDataValues : AddressDataValues {
    override val cities: Array<String>
        get() = Companion.cities

    override val streetNames: Array<String>
        get() = Companion.streetNames

    override val addressSuffixes: Array<String>
        get() = Companion.addressSuffixes

    companion object {
        private val streetNames = arrayOf(
                "Ányos Pál", "Apród", "Aradi vértanúk", "Aranyeső", "Arany János", "Aranyoskút",
                "Árpád", "Árvalányhaj", "Árva", "Átrium", "Aulich Lajos", "Avar", "Bagolyvári",
                "Bajcsy-Zsilinszky Endre", "Bakony", "Baláca", "Baláca", "Balassi Bálint", "Balaton", "Bányai",
                "Barack", "Barlangász", "Bartók Béla", "Batsányi János", "Batthyány Lajos", "Bedevölgy", "Béla",
                "Bem József", "Bercsényi Miklós", "Berkenye", "Berkenye", "Betongyár", "Bezerédi", "Billege",
                "Bogáncs", "Boglárka", "Bogyó", "Boksa", "Bolgár Mihály", "Boróka", "Borsos József",
                "Bosnyákárok", "Botev", "Bottrop", "Brusznyai Árpád", "Budapest", "Buhim", "Búzavirág",
                "Buzogány", "Buzogány", "Carlos Perez", "Céhház", "Cholnoky Jenő", "Cholnoky -", "Ciklámen",
                "Cincér", "Cinege", "Csákány", "Csalogány", "Csapó", "Csap", "Csatárhegyi bekötő",
                "Csatár", "Csemete", "Cséplő", "Cseralja", "Cserepes", "Csererdő", "Cserhát",
                "Cseri", "Csermák Antal", "Csermák", "Csikász Imre", "Csillag", "Csimorka", "Csizmadia",
                "Csutorás", "Dallos", "Damjanich János", "Deák Ferenc", "Déli", "Diófa", "Dióssy Márton",
                "Donáti", "Dornyai Béla", "Dózsa György", "Dózsa György", "Dugovics Titusz", "Egres", "Egry József",
                "Egyetem", "Eke", "Ék", "Előd", "Endrődi Sándor", "Eötvös Károly", "Eper",
                "Erdész", "Erdősáv", "Eresztvényi", "Erkel Ferenc", "Erzsébet", "Erzsébet", "Északi",
                "Észak-keleti", "Esze Tamás", "Eszterházy Antal", "Faiskola", "Fakopáncs", "Fáskert", "Fecske",
                "Fejesvölgy", "Feketeér", "Felsőújsor", "Fenyves", "Festő", "Flórián", "Forrás",
                "Fortuna", "Főposta", "Francsics", "Fülemüle", "Füredi", "Fűrész", "Fűrész",
                "Fürt", "Füttyös", "Füzesi", "Fűzfa", "Gábor Áron", "Galamb", "Gátfő",
                "Gébics", "Gelemér", "Gelencsér", "Gerenda", "Gizella", "Gladsaxe", "Gól",
                "Gombkötő", "Görbe", "Görgey Artúr", "Gubacs", "Gulyadombi", "Gyepes", "Gyertya",
                "Gyökeres", "Gyöngyvirág", "Győri", "Hajlat", "Hajmáskéri", "Hajnal", "Halastói",
                "Halle", "Hamuház", "Háncs", "Hangya", "Harangvirág", "Haraszt", "Harkály",
                "Harmat", "Hársfa", "Haszkovó", "Házgyári", "Hegyalja", "Hegybíró", "Henger",
                "Hérics", "Hidegkút", "Hoffer Ármin", "Hold", "Hordó", "Horgos", "Hóvirág",
                "Hóvirág", "Hunyadi János", "Huszár", "Ibolya", "Ifjúság", "Ipari", "Ipar",
                "Iskola", "Ívelő", "Jázmin", "Jogar", "Jókai Mór", "Józan", "József Attila",
                "Juhar", "Jutasi", "Kabay János", "Kádártai", "Kádár", "Kakukkfű", "Kálistó",
                "Kálmán", "Kalmár", "", "Kálvária", "Kálvin János", "Kankalin", "Kapitány",
                "Kápolna", "Káposztáskert", "Karacs Teréz", "Kard", "Kastélykert", "Kastély", "Kaszavölgy",
                "Kavics", "Kazán", "Kazán", "Keleti", "Kemecse", "Kenderföld", "Kenderike",
                "Kengyel", "Kéreg", "Kerekes", "Kereszt", "Kertalja", "Kerti", "Kert",
                "Kígyó", "Kilátó", "Kincsási", "Kinizsi", "Kisállomás", "Kisfaludy Sándor", "Kiskőrösi",
                "Kisréti", "Kiss", "Kistelek", "Kistó", "Kisvölgyi", "Kittenberger Kálmán", "Klapka György",
                "Kocsis", "Kodály Zoltán", "Kollégium", "Kolostor", "Komakút", "Kopácsi", "Kopácsi",
                "Kórház", "Korona", "Kossuth Lajos", "Kossuth Lajos", "Kőalja", "Kőbánya", "Köd",
                "Kőhíd", "Kökény", "Kökörcsin", "Kölcsey Ferenc", "Kőris", "Körtefa", "Kövesdombi",
                "Középhát", "Kupa", "Külső Kádártai", "Külső-Kádártai", "Kürt", "Láhner György", "Lánci",
                "Lánczi", "László", "Látóhegy", "Lázár", "Leányka", "Lejtős", "Létra",
                "Levendula", "Liget", "Lilaakác", "Liliom", "Liszt Ferenc", "Lóczy Lajos", "Lődomb",
                "Lőszergyári", "Lövőház", "Löwey Klára", "Madách Imre", "Magyali", "Major", "Május 1.",
                "Málna", "Malomkert", "Malomkő", "Malom", "Mandulafa", "Március 15.", "Margit",
                "Martinovics Ignác", "Martinovics Ignác", "Mártírok", "Mátyás", "Meggyfa", "Megyeház", "Megyeház",
                "Méhes", "Mély", "Menyekei", "Mester", "mezítlábas", "Mikládi", "Miklós",
                "Mikszáth Kálmán", "Mindszenty József", "Mogyoró", "Moha", "Molnárhegyi", "Móra Ferenc", "Móricz Zsigmond",
                "Munkácsy Mihály", "Muskátli", "Muskotály", "Nagycsarnok", "Nagy László", "Nagymező", "Nagytó",
                "Nagyvíz", "Napsugár", "Nap", "Nárcisz", "Nefelejcs", "Német", "Névtelen",
                "Nyárfa", "Nyerges", "Nyugati", "Orgona", "Ostrom", "Oszlop", "Ottignies",
                "Óvári Ferenc", "Óváros", "Óváros", "Óvoda", "Ördögárok", "Öregrét", "Őrház",
                "", "Paál László", "Pacsirta", "Pajta", "Palást", "Palló", "Pápai",
                "Papod", "Papvásár", "Párna", "Pásztor", "Patak", "Pázmándi", "Petőfi Sándor",
                "Pillér", "Pipacs", "Piramis", "Poeltenberg Ernő", "Pogánytelki", "Posta", "Posztós",
                "Pöröly", "Prépost", "Próder Ferenc", "Puskin", "Püspökréti", "Radnóti Miklós", "Rákóczi Ferenc",
                "Ranolder János", "Reguly Antal", "Reinitz Béla", "Remete", "Répavölgyi", "Rezeda", "Ribiszke",
                "Rigó", "Roboz", "Rómer Flóris", "Rovaniemi", "Rozmaring", "Rozoga", "Rózsa",
                "Rönk", "Sáfrány", "Sáncközi", "Sarkantyús", "Sarló", "Sarok", "Sarolta",
                "Séd", "Semmelweis Ignác", "Sepsiszentgyörgy", "Seregély", "", "Sigray", "Simon István",
                "Síp", "Sólyi", "Sorház", "Sorompó", "Sóskaárok", "Stadion", "Stadion",
                "Stromfeld Aurél", "Sudár", "Szabadság", "Szabó", "Szajkó", "Szalonka", "Szán",
                "Szarkaláb", "Szarvas", "Széchenyi István", "Szeder", "Szegfű", "Szeglethy György", "Szekerce",
                "Szél", "Szendrey Júlia", "Szent Imre", "Szent István", "Szent István", "Szent István", "Szent Katalin",
                "Szent Margit", "", "Szérűskert", "Szigethi József", "Sziklay János", "Szikra", "Szilfa",
                "Szilvádi", "Szilvádi", "Szirom", "Szivárvány", "Szófia", "Szöcske", "Szőlőhegy",
                "Szömörce", "Szövetkezet", "Szűcs", "Takácskert", "Táncsics Mihály", "Tartu", "Tátika",
                "Tátorján", "Teleki Blanka", "Temetőhegy", "Templom", "Thököly", "Tikhegyi", "Tímár",
                "Tirat-Carmel", "Tiszafa", "Tiszafa", "Tizenháromváros", "Tobak", "Toborzó", "Torzsa",
                "Tószeg", "Tölgyfa", "Török Ignác", "Tulipán", "", "Tücsök", "Tüske",
                "Tüzér", "Újkuti", "Úrkút", "Vadaspark", "Vadász", "Vadvirág", "Vajda János",
                "Vakcsai", "Vámosi", "Varga", "Vár", "Vár", "Vasas", "Vas Gereben",
                "Vasút", "Vécsey Károly", "Venyige", "Veres Péter", "Vértanúk", "Vessző", "Veszprémi",
                "Veszprémvölgyi", "Victor Hugo", "Villám", "Vilonyai",
                "Viola", "Virág Benedek", "Vitéz", "Vízi", "Vízvezeték", "Völgyhíd", "Völgyikút",
                "Völgykúti", "Vörösbegy", "Vörösmarty Mihály", "Wartha Vince", "Zalagyöngye", "Zápor", "Zirci",
                "Zrínyi Miklós", "Zuzmó", "Zsilip"
        )
        private val addressSuffixes = arrayOf("árok", "átjáró", "dűlő", "dűlőút", "erdősor", "fasor", "forduló",
                "gát", "határsor", "határút", "kapu", "körönd", "körtér", "körút",
                "köz", "lakótelep", "lejáró", "lejtő", "lépcső", "liget", "mélyút",
                "orom", "ösvény", "park", "part", "pincesor", "rakpart", "sétány",
                "sikátor", "sor", "sugárút", "tér", "udvar", "út", "utca",
                "üdülőpart")
        private val cities = arrayOf("Aba", "Abádszalók", "Abaújszántó", "Abony", "Ács", "Adony", "Ajak",
                "Ajka", "Albertirsa", "Alsózsolca", "Aszód", "Bábolna", "Bácsalmás", "Badacsonytomaj",
                "Baja", "Baktalórántháza", "Balassagyarmat", "Balatonalmádi", "Balatonboglár", "Balatonföldvár", "Balatonfüred",
                "Balatonfűzfő", "Balatonkenese", "Balatonlelle", "Balkány", "Balmazújváros", "Barcs", "Bátaszék",
                "Bátonyterenye", "Battonya", "Békés", "Békéscsaba", "Bélapátfalva", "Beled", "Berettyóújfalu",
                "Berhida", "Besenyszög", "Biatorbágy", "Bicske", "Biharkeresztes", "Bodajk", "Bóly",
                "Bonyhád", "Borsodnádasd", "Budakalász", "Budakeszi", "Budaörs", "Budapest", "Bük",
                "Cegléd", "Celldömölk", "Cigánd", "Csákvár", "Csanádpalota", "Csenger", "Csepreg",
                "Csongrád", "Csorna", "Csorvás", "Csurgó", "Dabas", "Debrecen", "Demecser",
                "Derecske", "Dévaványa", "Devecser", "Diósd", "Dombóvár", "Dombrád", "Dorog",
                "Dunaföldvár", "Dunaharaszti", "Dunakeszi", "Dunaújváros", "Dunavarsány", "Dunavecse", "Edelény",
                "Eger", "Elek", "Emőd", "Encs", "Enying", "Ercsi", "Érd",
                "Esztergom", "Fegyvernek", "Fehérgyarmat", "Felsőzsolca", "Fertőd", "Fertőszentmiklós", "Fonyód",
                "Fót", "Füzesabony", "Füzesgyarmat", "Gárdony", "Göd", "Gödöllő", "Gönc",
                "Gyál", "Gyomaendrőd", "Gyömrő", "Gyöngyös", "Gyöngyöspata", "Gyönk", "Győr",
                "Gyula", "Hajdúböszörmény", "Hajdúdorog", "Hajdúhadház", "Hajdúnánás", "Hajdúsámson", "Hajdúszoboszló",
                "Hajós", "Halásztelek", "Harkány", "Hatvan", "Herend", "Heves", "Hévíz",
                "Hódmezővásárhely", "Ibrány", "Igal", "Isaszeg", "Izsák", "Jánoshalma", "Jánosháza",
                "Jánossomorja", "Jászapáti", "Jászárokszállás", "Jászberény", "Jászfényszaru", "Jászkisér", "Kaba",
                "Kadarkút", "Kalocsa", "Kaposvár", "Kapuvár", "Karcag", "Kazincbarcika", "Kecel",
                "Kecskemét", "Kemecse", "Kenderes", "Kerekegyháza", "Kerepes", "Keszthely", "Kisbér",
                "Kisköre", "Kiskőrös", "Kiskunfélegyháza", "Kiskunhalas", "Kiskunmajsa", "Kistarcsa", "Kistelek",
                "Kisújszállás", "Kisvárda", "Komádi", "Komárom", "Komló", "Kondoros", "Kozármisleny",
                "Körmend", "Körösladány", "Kőszeg", "Kunhegyes", "Kunszentmárton", "Kunszentmiklós", "Lábatlan",
                "Lajosmizse", "Lébény", "Lengyeltóti", "Lenti", "Létavértes", "Letenye", "Lőrinci",
                "Maglód", "Mágocs", "Makó", "Mándok", "Marcali", "Máriapócs", "Martfű",
                "Martonvásár", "Mátészalka", "Medgyesegyháza", "Mélykút", "Mezőberény", "Mezőcsát", "Mezőhegyes",
                "Mezőkeresztes", "Mezőkovácsháza", "Mezőkövesd", "Mezőtúr", "Mindszent", "Miskolc", "Mohács",
                "Monor", "Mór", "Mórahalom", "Mosonmagyaróvár", "Nádudvar", "Nagyatád", "Nagybajom",
                "Nagyecsed", "Nagyhalász", "Nagykálló", "Nagykanizsa", "Nagykáta", "Nagykőrös", "Nagymányok",
                "Nagymaros", "Nyékládháza", "Nyergesújfalu", "Nyíradony", "Nyírbátor", "Nyíregyháza", "Nyírlugos",
                "Nyírmada", "Nyírtelek", "Ócsa", "Onga", "Orosháza", "Oroszlány", "Ózd",
                "Őrbottyán", "Őriszentpéter", "Örkény", "Pacsa", "Paks", "Pálháza", "Pannonhalma",
                "Pápa", "Pásztó", "Pécel", "Pécs", "Pécsvárad", "Pétervására", "Pilis",
                "Piliscsaba", "Pilisvörösvár", "Polgár", "Polgárdi", "Pomáz", "Pusztaszabolcs", "Putnok",
                "Püspökladány", "Rácalmás", "Ráckeve", "Rakamaz", "Rákóczifalva", "Répcelak", "Rétság",
                "Rudabánya", "Sajóbábony", "Sajószentpéter", "Salgótarján", "Sándorfalva", "Sárbogárd", "Sarkad",
                "Sárospatak", "Sárvár", "Sásd", "Sátoraljaújhely", "Sellye", "Siklós", "Simontornya",
                "Siófok", "Solt", "Soltvadkert", "Sopron", "Sülysáp", "Sümeg", "Szabadszállás",
                "Szarvas", "Százhalombatta", "Szécsény", "Szeged", "Szeghalom", "Székesfehérvár", "Szekszárd",
                "Szendrő", "Szentendre", "Szentes", "Szentgotthárd", "Szentlőrinc", "Szerencs", "Szigethalom",
                "Szigetszentmiklós", "Szigetvár", "Szikszó", "Szob", "Szolnok", "Szombathely", "Tab",
                "Tamási", "Tápiószele", "Tapolca", "Tát", "Tata", "Tatabánya", "Téglás",
                "Tét", "Tiszacsege", "Tiszaföldvár", "Tiszafüred", "Tiszakécske", "Tiszalök", "Tiszaújváros",
                "Tiszavasvári", "Tokaj", "Tolna", "Tompa", "Tótkomlós", "Tököl", "Törökbálint",
                "Törökszentmiklós", "Tura", "Túrkeve", "Újfehértó", "Újhartyán", "Újkígyós", "Újszász",
                "Üllő", "Vác", "Vaja", "Vámospércs", "Várpalota", "Vásárosnamény", "Vasvár",
                "Vecsés", "Velence", "Vép", "Veresegyház", "Verpelét", "Veszprém", "Vésztő",
                "Villány", "Visegrád", "Záhony", "Zalaegerszeg", "Zalakaros", "Zalalövő", "Zalaszentgrót",
                "Zamárdi", "Zirc", "Zsámbék")
    }
}